//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMenu()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int MenuID { get; set; }
        public Nullable<int> Pizza { get; set; }
        public Nullable<int> Chicken { get; set; }
        public Nullable<int> Sandwich { get; set; }
        public Nullable<int> Pasta { get; set; }
        public Nullable<int> Soup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
